const MONTHLY_PASSWORD = '午前2時';
const TERMS_VERSION = '2026-04-29-v9';
const PATTERN_SIZE = 12;
const PATTERN_TOTAL = PATTERN_SIZE * PATTERN_SIZE;
let TERMS_TEXT = '利用規約を読み込み中です…';
fetch('terms.txt').then(r => r.text()).then(t => { TERMS_TEXT = t; render(); }).catch(() => {});
const ASSETS = window.characterAssets || { hero: 'alpaca-promo.png', head: 'alpaca-promo.png' };

const qs = [
  ['🖼️','飲み会のお店に、ちょっと攻めた恋愛系ポスターが貼ってあったら？',[[ '「攻めてるね」と笑って話題にする',{E:2,P:1},{flirt:2,close:1}],['ちょっと気になって見ちゃう',{N:1,F:1},{flirt:1,guard:1}],['見てないふりをする',{I:1,J:1},{guard:2}],['友達にツッコんで流す',{E:1,T:1},{guard:1,flirt:1}]]],
  ['🎤','カラオケで、気になる人が色っぽい曲を入れたら？',[[ '正直かなり見ちゃう',{E:1,P:1},{close:2,flirt:2}],['ドキッとして聴く',{F:1,N:1},{sweet:1,close:1}],['平静を装って拍手する',{T:1,J:1},{guard:1}],['飲み物を取りに行く',{I:2,J:1},{guard:3}]]],
  ['🏆','飲み会で「この中で一番色気あるの誰？」となったら？',[[ '自分も候補に入りたい',{E:2,P:1},{flirt:2,close:1}],['気になる人をこっそり選ぶ',{F:1,N:1},{flirt:1,sweet:1}],['友達を立てる',{F:2,J:1},{sweet:2}],['その話題から逃げる',{I:2,J:1},{guard:2}]]],
  ['🛗','エレベーターで、気になる人と知らない人1人の3人。微妙な沈黙になったら？',[[ '目が合ったら「ふふっ」と笑う',{E:1,F:1},{flirt:2,sweet:1}],['ちょっとだけ距離を近めに立つ',{E:1,P:1},{close:3,flirt:1}],['何も起きてない顔をする',{I:1,T:1},{guard:1,consent:1}],['スマホに逃げる',{I:2,J:1},{guard:3}]]],
  ['🎲','罰ゲームで「好きなタイプをちょっと具体的に言う」ことになったら？',[[ 'かなり具体的に言う',{E:2,F:1},{flirt:2,close:1}],['ちょっと匂わせる',{N:1,P:1},{flirt:3}],['無難にごまかす',{T:1,J:1},{guard:1}],['全力で逃げる',{I:2,J:1},{guard:3}]]],
  ['📱','スマホに“夜向け恋愛診断”の広告が出てきたら？',[[ 'その場で開いてみる',{E:1,P:1},{flirt:2,close:1}],['友達に見せて笑う',{E:2,F:1},{flirt:1}],['気になるけどあとで見る',{I:1,N:1},{guard:1,flirt:1}],['恥ずかしくて閉じる',{I:2,J:1},{guard:2}]]],
  ['💬','みんなで恋バナ中、「どこからが脈あり？」となったら？',[[ '距離が近くなったら脈あり',{F:1,P:1},{close:2}],['返信が続いたら脈あり',{N:1,F:1},{sweet:1}],['二人で会えたら脈あり',{J:1,F:1},{consent:1}],['はっきり言われるまで信じない',{T:1,J:2},{guard:2,consent:2}]]],
  ['👀','友達に「今日あの人と距離近くない？」と言われたら？',[[ '「バレた？」と返す',{E:2,P:1},{flirt:3,close:1}],['笑ってごまかす',{F:1,P:1},{flirt:1,guard:1}],['「そうかな？」と探る',{N:1,J:1},{guard:1,flirt:1}],['急に恥ずかしくなる',{I:2,F:1},{guard:2,sweet:1}]]],
  ['🎶','飲み会のBGMが急に甘いラブソングになったら？',[[ '「この曲いいよね」と話題にする',{E:1,N:1},{flirt:2,music:1}],['ちょっとだけ気になる人を意識する',{F:1,N:1},{sweet:1,close:1}],['何もない顔で聞く',{T:1,J:1},{guard:1}],['曲に気づかないふりをする',{I:2,J:1},{guard:2}]]],
  ['✨','気になる人が自分の香水や服を褒めてきたら？',[[ 'かなり嬉しくて近づく',{E:1,F:1},{close:3,sweet:1}],['照れつつ喜ぶ',{F:2},{sweet:2,guard:1}],['どういう意味か考える',{N:1,J:1},{guard:1,flirt:1}],['反応に困る',{I:2,T:1},{guard:2}]]],
  ['🍷','気になる人のグラスが空きそう。もう少し話したいときは？',[[ '「次なにいく？」と軽く聞く',{E:1,P:1},{close:2,flirt:1}],['「これおいしかったよ」と軽くすすめる',{F:1,N:1},{sweet:1,flirt:1,close:1}],['「まだ飲めそうなら一緒に頼む？」と聞く',{F:1,J:1},{consent:3,guard:1}],['無理に誘わず様子を見る',{I:1,J:2},{guard:2,consent:1}]]],
  ['🌙','相手から「もうちょっと話してたい」と言われたら？',[[ 'かなり嬉しくて残る',{E:1,F:1},{close:2,sweet:1}],['雰囲気が良ければ残る',{N:1,P:1},{flirt:1,close:1}],['時間を見て考える',{T:1,J:1},{consent:1,guard:1}],['ちゃんと帰る',{I:1,J:2},{guard:2}]]],
  ['😏','気になる人に「今日、ちょっと雰囲気ちがうね」と言われたら？',[[ '「気づいた？」と返す',{E:2,P:1},{flirt:3}],['照れつつ「そうかな？」と笑う',{F:1,N:1},{sweet:1,flirt:1}],['本気か冗談か探る',{N:1,J:1},{guard:1,consent:1}],['反応に困って話題を変える',{I:2,J:1},{guard:3}]]],
  ['🫧','いい感じの雰囲気で、確認するなら？',[[ '「このまま一緒にいていい？」',{E:1,F:1},{consent:3,close:2}],['「もう少し話す？」',{F:1,N:1},{consent:2,sweet:1}],['「帰り大丈夫？」',{F:2,J:1},{consent:2,guard:1,sweet:1}],['自分からは聞けない',{I:2,F:1},{guard:3,sweet:1}]]],
  ['😺','好きな人から軽くからかわれたら？',[[ '乗っかって返す',{E:2,P:1},{flirt:3}],['照れながら返す',{F:1,N:1},{sweet:1,flirt:1}],['本気か冗談か探る',{N:1,J:1},{guard:1,flirt:1}],['うまく返せない',{I:2,J:1},{guard:2}]]],
  ['📸','気になる人と写真を撮る流れになったら？',[[ '近めで撮る',{E:1,P:1},{close:3}],['ちょっと距離を詰める',{F:1,N:1},{close:2,flirt:1}],['普通の距離で撮る',{S:1,J:1},{consent:1,guard:1}],['写るのが少し苦手',{I:2,J:1},{guard:2}]]],
  ['💘','最後に、あなたが一番弱い演出は？',[[ '近い距離で褒められる',{F:1,N:1},{close:2,sweet:1}],['少しからかわれる',{P:1,E:1},{flirt:2}],['ふたりだけの空気になる',{I:1,N:1},{close:1,flirt:1}],['安心できる言葉をもらう',{F:2,J:1},{consent:2,sweet:1}]]]
];


const names={ENFP:['深夜エンターテイナー','距離感バグらせ小悪魔'],ENFJ:['飲み会プロデューサー','甘やかし沼メーカー'],ENTP:['ツッコミ無双の策士','口説き文句が冗談に聞こえる人'],ENTJ:['二次会支配人','主導権握りがちナイトリーダー'],ESFP:['朝までパーティー番長','その場の空気で恋が始まる人'],ESFJ:['みんなの世話焼き乾杯係','酔うと距離が近い世話焼き'],ESTP:['終電クラッシャー','終電後に強すぎる危険人物'],ESTJ:['幹事長タイプ','ちゃんとしてるのに夜だけ大胆'],INFP:['静かな沼タイプ','好きになると重めロマンチスト'],INFJ:['深夜の聞き上手','目が合うだけで沼らせる人'],INTP:['考えすぎ哲学酔い','理屈っぽいのに不意に甘い'],INTJ:['クールな観察者','落とす気ないのに刺さる人'],ISFP:['気分で覚醒アーティスト','雰囲気で全部持っていく人'],ISFJ:['安心感の毛布','安心させてから沼らせる人'],ISTP:['一匹狼カラオケ職人','無口なのに距離感がずるい'],ISTJ:['終電守護神','誠実そうで夜にギャップ出る人']};
const blurbs={ENFP:'その場を明るくする天才。好きな人には意外と考えすぎる朝3時タイプ。',ENFJ:'全員の空気を見て、気づけば場を支配しているやさしい司会者。',ENTP:'会話の瞬発力で距離を詰める。冗談の中に本音を混ぜがち。',ENTJ:'二次会の行き先も席順も決められる夜の司令塔。',ESFP:'楽しい空気の中心。勢いで一番ドラマを起こすタイプ。',ESFJ:'気配りでみんなを包む。酔うと少し距離が近くなる。',ESTP:'ノリと行動力の塊。終電後から本領発揮。',ESTJ:'ちゃんとしているから信頼される。だけど夜にギャップが出る。',INFP:'静かなのに記憶に残る。深い話で急に沼らせる。',INFJ:'聞き上手すぎて相手が勝手に心を開く。視線が強い。',INTP:'酔っても分析している。たまに出る甘さがずるい。',INTJ:'落ち着いた観察者。狙ってない一言が妙に刺さる。',ISFP:'気分が乗った瞬間だけ誰よりも魅力的。雰囲気で勝つ。',ISFJ:'安心感がすごい。気づいたら隣にいてほしい存在。',ISTP:'無口だけど行動で見せる。カラオケ選曲にセンスが出る。',ISTJ:'終電を守る理性派。誠実さとギャップでじわじわ強い。'};
let state={mode:'home',flow:'solo',step:0,aAns:[],termsOK:false,unlocked:false,pass:'',codeA:'',codeB:'',codeError:''};
const app=document.getElementById('app');
function addScores(t,o){Object.entries(o||{}).forEach(([k,v])=>t[k]=(t[k]||0)+v)}
function typeFrom(ans){const s={E:0,I:0,S:0,N:0,T:0,F:0,J:0,P:0};ans.forEach((a,i)=>addScores(s,qs[i]?.[2]?.[a]?.[1]));return `${s.E>=s.I?'E':'I'}${s.S>=s.N?'S':'N'}${s.T>=s.F?'T':'F'}${s.J>=s.P?'J':'P'}`}
function scores(ans){const n={party:0,karaoke:0,distance:0,midnight:0,music:0,care:0,close:0,consent:0,flirt:0,sweet:0,guard:0};ans.forEach((a,i)=>addScores(n,qs[i]?.[2]?.[a]?.[2]));return n}
function bucket(v,max=12){return Math.max(0,Math.min(3,Math.floor((v/max)*4)))}
function normCode(c){return String(c||'').toUpperCase().replace(/[^0-9A-Z]/g,'').slice(0,8)}
function hash36(str,len){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36).toUpperCase().padStart(len,'0').slice(-len)}
function patternFromAnswers(type,ans){const n=scores(ans);let weighted=0;ans.forEach((a,i)=>weighted+=(a+1)*(i+3));const packed={consent:bucket(n.consent,10),close:bucket(n.close+n.distance,18),guard:bucket(n.guard,16),flirt:bucket(n.flirt,14)};const x=((weighted+packed.close*3+packed.flirt*5+type.charCodeAt(0))%PATTERN_SIZE)+1;const y=((Math.abs(n.party*3+n.distance*5+n.midnight*7+n.music*11+n.karaoke*13+n.care*17+n.close*19+n.consent*23+n.flirt*29+n.sweet*31+n.guard*37)+packed.consent*7+packed.guard*11)%PATTERN_SIZE)+1;const pattern=(x-1)*PATTERN_SIZE+y;const prefix=(pattern-1).toString(36).toUpperCase().padStart(2,'0');const core=prefix+packed.consent+packed.close+packed.guard+packed.flirt;return{x,y,pattern,code:core+hash36(core+'|'+type+'|'+TERMS_VERSION,2),n,packed,type}}
function decodeCode(raw){const code=normCode(raw);if(!/^[0-9A-Z]{8}$/.test(code))return null;const p=parseInt(code.slice(0,2),36);if(!Number.isFinite(p)||p<0||p>=PATTERN_TOTAL)return null;const parts={consent:parseInt(code[2],36),close:parseInt(code[3],36),guard:parseInt(code[4],36),flirt:parseInt(code[5],36)};if(Object.values(parts).some(v=>!Number.isFinite(v)||v<0||v>3))return null;const pattern=p+1;return{code,pattern,x:Math.floor(p/PATTERN_SIZE)+1,y:(p%PATTERN_SIZE)+1,packed:parts}}
function complement(a,b,key){const A=a.packed[key],B=b.packed[key];if(key==='consent'){return [[6,8,8,10],[8,7,8,8],[8,8,6,5],[10,8,5,-8]][A][B]}if(key==='guard'){return [[6,7,5,2],[7,8,7,4],[5,7,8,7],[2,4,7,6]][A][B]}if(key==='close'){return [[8,7,5,2],[7,8,7,4],[5,7,8,7],[2,4,7,6]][A][B]}if(key==='flirt'){return [[6,7,5,3],[7,8,7,5],[5,7,8,7],[3,5,7,6]][A][B]}return 0}
function codeCompatibility(a,b){const dx=Math.abs(a.x-b.x),dy=Math.abs(a.y-b.y);let score=48;score+=Math.max(0,24-dx*4)+Math.max(0,24-dy*4);score+=complement(a,b,'consent')+complement(a,b,'close')+complement(a,b,'guard')+complement(a,b,'flirt');score=Math.max(32,Math.min(99,Math.round(score)));return{score,distance:dx+dy}}
function dominantAxis(a,b){const sum={consent:a.packed.consent+b.packed.consent,close:a.packed.close+b.packed.close,guard:a.packed.guard+b.packed.guard,flirt:a.packed.flirt+b.packed.flirt};if(Math.abs(a.packed.consent-b.packed.consent)>=3)return 'consentComplement';if(sum.consent>=5)return 'consent';if(sum.close>=5)return 'close';if(sum.flirt>=5)return 'flirt';if(sum.guard>=5)return 'guard';return Object.entries(sum).sort((x,y)=>y[1]-x[1])[0][0]}
function resultText(a,b,c){const axis=dominantAxis(a,b);const high=c.score>=95;const top=high?'近づくほど、空気が変わるふたり':'ふたりの夜の噛み合い';const map={consentComplement:['言える人 × 聞けない人の補完型','片方が言葉で安心を作れて、もう片方がその確認を受け取ることで自然にほどけやすい組み合わせです。急に攻めるより、「このまま一緒にいていい？」のような一言がかなり刺さります。','本音を言える空気づくりが鍵。聞けない側が断れる余白まであると最強。'],consent:['言葉で安心させられるふたり','ドキッとする空気になっても、確認できるから怖くない。勢いだけではなく、ちゃんと安心を作れる大人っぽい相性です。','おすすめは「もう少し話す？」の一言。安心できる色気が刺さります。'],close:['距離が近いほど自然になるふたり','隣に座る、歩幅が合う、目が合う。それだけで空気が変わりやすい組み合わせです。無理に盛り上げなくても、近くにいるほど温度が上がります。','急展開より、帰り道やカウンター席の近さが効きます。'],flirt:['からかいと照れが噛み合うふたり','冗談のつもりが、気づいたら本音っぽくなるタイプ。軽いからかい、匂わせ、照れ笑いのラリーで一気に距離が縮まりやすいです。','やりすぎず、相手が笑って返せる範囲がいちばん強いです。'],guard:['慎重なのに、なぜか安心できるふたり','どちらか、または両方にガードがあるからこそ、雑に近づかない相性です。急がない分、信頼ができたときに深くなりやすい組み合わせ。','焦らず、帰り際の優しい一言が効きます。']};const t=map[axis]||map.consent;return`<div class="resultText"><h4>${high?top:t[0]}</h4><p class="hint">${t[0]}</p><p>${t[1]}</p><p>${t[2]}</p></div>`}
function rank(sc){return sc>=90?'深夜まで一緒にいたくなる相性':sc>=80?'カラオケで距離が縮まる相性':sc>=70?'飲み会で自然に隣になる相性':sc>=60?'友達から始まる安定相性':'探り合いから始まる相性'}
function stats(n){return `<div class="stats">${[['距離感',n.close+n.distance],['同意/安心',n.consent],['慎重さ',n.guard],['駆け引き',n.flirt],['甘え受容',n.sweet]].map(([k,v])=>`<div><span>${k}</span><i><b style="width:${Math.min(100,v*14)}%"></b></i></div>`).join('')}</div>`}
function codeParts(p){return `<div class="codeParts"><div><span>consent</span><b>${p.consent}</b><small>確認</small></div><div><span>close</span><b>${p.close}</b><small>距離</small></div><div><span>guard</span><b>${p.guard}</b><small>慎重</small></div><div><span>flirt</span><b>${p.flirt}</b><small>駆け引き</small></div></div>`}
function esc(s){return String(s).replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]))}
function home(){return `<section class="card hero"><div><div class="badge">✨ Deep Night相性</div><h1>Paka姉 裏診断</h1><p>17問で、夜の距離感を診断。8桁コードに consent / close / guard / flirt を圧縮して、99%でも軸ごとに結果文が変わります。</p><div class="actions"><button data-act="solo">💕 ひとりで診断する</button><button class="secondary" data-act="pair">👥 ふたりで相性診断する</button></div><p class="mini">※これはエンタメ用の16タイプ風診断です。</p></div><div><img src="${ASSETS.hero}" alt="夜のPaka姉"><div class="phone"><b>軸別結果</b><strong>99%</strong><span>補完相性対応</span></div></div></section>`}
function terms(){return `<section class="card center terms"><img class="miniChar" src="${ASSETS.head}" alt="Paka姉"><div class="alpaca">🦙📜</div><h2>利用規約への同意</h2><p class="lead">診断を始める前に、利用規約を確認してください。</p><div class="termsBox"><pre>${esc(TERMS_TEXT)}</pre></div><label class="agree"><input id="termsOK" type="checkbox" ${state.termsOK?'checked':''}>利用規約に同意します</label><button data-act="termsNext" ${state.termsOK?'':'disabled'}>同意して進む</button><button class="ghost" data-act="home">戻る</button></section>`}
function start(){return `<section class="card center"><img class="miniChar" src="${ASSETS.head}" alt="Paka姉"><div class="alpaca">🦙💕</div><h2>17問で夜の距離感を診断します</h2><p class="lead">MBTI入力は不要。診断結果で、ふたり相性用の8桁コードを発行します。</p><button data-act="startQuiz">診断する</button><button class="ghost" data-act="home">戻る</button></section>`}
function codeInput(){return `<section class="card center codeInput"><img class="miniChar" src="${ASSETS.head}" alt="Paka姉"><div class="alpaca">🦙🔐</div><h2>8桁コードで相性診断</h2><p class="lead">あなたと相手のコードを入力してください。コードには144パターン番号と4つの補完軸が入っています。</p><div class="grid2"><label class="field"><span>あなたの8桁コード</span><input id="codeA" maxlength="8" value="${esc(state.codeA)}" placeholder="例：03ABC123"></label><label class="field"><span>相手の8桁コード</span><input id="codeB" maxlength="8" value="${esc(state.codeB)}" placeholder="例：1ZPAX999"></label></div>${state.codeError?`<div class="error">${state.codeError}</div>`:''}<div class="actions" style="justify-content:center"><button data-act="codeCompat">相性診断する</button><button class="ghost" data-act="soloFromCode">コードを発行する</button><button class="ghost" data-act="home">戻る</button></div></section>`}
function quiz(){const q=qs[state.step];return `<section class="card quiz"><div class="progress"><span>あなたの診断</span><b>${state.step+1}/${qs.length}</b></div><div class="bar"><i style="width:${(state.step+1)/qs.length*100}%"></i></div><div class="qIcon">${q[0]}</div><h2>${q[1]}</h2><div class="options">${q[2].map((o,i)=>`<button data-answer="${i}"><b>${String.fromCharCode(65+i)}</b>${o[0]}</button>`).join('')}</div></section>`}
function result(){const type=typeFrom(state.aAns),p=patternFromAnswers(type,state.aAns);return `<section class="results"><div class="card result codePair"><img class="miniChar" src="${ASSETS.head}" alt="Paka姉"><div class="alpaca">🦙✨</div><div class="badge">🍷 診断結果</div><h2>${type}</h2><h3>${names[type][0]}</h3><p class="lead">${blurbs[type]}</p><div class="codeBox"><span>相性診断用 8桁コード</span><strong>${p.code}</strong><small>144パターン番号：${p.pattern} / X${p.x}-Y${p.y}</small></div>${codeParts(p.packed)}${stats(p.n)}<a class="btn share" target="_blank" href="https://twitter.com/intent/tweet?text=${encodeURIComponent(`Paka姉 裏診断をやったよ。私は${type}「${names[type][0]}」 / 相性コード ${p.code} 🦙💕`)}">結果をシェアする</a></div><div class="card secret"><img class="miniChar" src="${ASSETS.head}" alt="Paka姉"><h3>🔒 深夜モード</h3><p>合言葉を知っている人だけ、もう一段ドキッとする結果を見られます。</p>${secret(type)}</div><button class="reset ghost" data-act="home">↻ もう一回やる</button></section>`}
function pairResult(){const a=decodeCode(state.codeA),b=decodeCode(state.codeB),c=codeCompatibility(a,b);return `<section class="results"><div class="card pair codePair"><div class="badge">💕 Deep Night相性</div><h2>${c.score}%</h2><h3>${rank(c.score)}</h3><p class="lead">144パターン距離に加えて、consent / close / guard / flirt の補完関係を見ています。</p>${resultText(a,b,c)}<div class="pairCodes"><div><span>あなた</span><b>${a.code}</b><small>144番中 ${a.pattern}<br>X${a.x}-Y${a.y}</small></div><div><span>相手</span><b>${b.code}</b><small>144番中 ${b.pattern}<br>X${b.x}-Y${b.y}</small></div></div><div class="grid2">${codeParts(a.packed)}${codeParts(b.packed)}</div><ul><li>距離：${c.distance} / 22</li><li>99%でも、4軸の強さと補完関係によって結果文が変わります。</li></ul></div><div class="card secret"><img class="miniChar" src="${ASSETS.head}" alt="Paka姉"><h3>🔒 深夜モード</h3><p>合言葉を知っている人だけ、深夜版の相性コメントを見られます。</p>${state.unlocked?`<div class="unlocked"><h2>深夜相性 ${Math.min(99,c.score+7)}%</h2><p>急に攻めるより、帰り道の会話が一番刺さります。本音を言える空気づくりが鍵。</p></div>`:`<input id="pass" placeholder="今月の合言葉" value="${esc(state.pass)}"><button data-act="unlock">深夜モードを解放する</button><small>ヒント：公式Xや画像のどこかに隠す想定</small>`}</div><button class="reset ghost" data-act="codeBack">コード入力に戻る</button><button class="reset ghost" data-act="home">↻ 最初に戻る</button></section>`}
function secret(type){return state.unlocked?`<div class="unlocked"><h2>${names[type][1]}</h2><p>急に攻めるより、帰り道の会話が一番刺さります。隣に座ると空気が変わるタイプ。</p></div>`:`<input id="pass" placeholder="今月の合言葉" value="${esc(state.pass)}"><button data-act="unlock">深夜モードを解放する</button><small>ヒント：公式Xや画像のどこかに隠す想定</small>`}
function view(){return state.mode==='home'?home():state.mode==='terms'?terms():state.mode==='start'?start():state.mode==='codeInput'?codeInput():state.mode==='quiz'?quiz():state.mode==='soloResult'?result():state.mode==='pairResult'?pairResult():home()}
function render(){app.innerHTML=`<main class="wrap">${view()}</main>`;bind()}
function bind(){document.querySelectorAll('[data-act]').forEach(el=>el.onclick=()=>act(el.dataset.act));document.querySelectorAll('[data-answer]').forEach(el=>el.onclick=()=>answer(+el.dataset.answer));const t=document.getElementById('termsOK');if(t)t.onchange=e=>{state.termsOK=e.target.checked;render()};const ca=document.getElementById('codeA'),cb=document.getElementById('codeB'),pass=document.getElementById('pass');if(ca)ca.oninput=e=>state.codeA=normCode(e.target.value);if(cb)cb.oninput=e=>state.codeB=normCode(e.target.value);if(pass)pass.oninput=e=>state.pass=e.target.value}
function act(a){if(a==='solo'||a==='pair'){state={mode:'terms',flow:a,step:0,aAns:[],termsOK:false,unlocked:false,pass:'',codeA:'',codeB:'',codeError:''}}else if(a==='termsNext'){if(!state.termsOK)return;state.mode=state.flow==='pair'?'codeInput':'start'}else if(a==='startQuiz'){state.aAns=[];state.step=0;state.mode='quiz'}else if(a==='soloFromCode'){state.flow='solo';state.mode='start';state.aAns=[];state.step=0;state.codeError=''}else if(a==='codeCompat'){state.codeA=normCode(document.getElementById('codeA')?.value||state.codeA);state.codeB=normCode(document.getElementById('codeB')?.value||state.codeB);if(!decodeCode(state.codeA)||!decodeCode(state.codeB)){state.codeError='8桁の相性コードを2つ入力してください。';state.mode='codeInput'}else{state.mode='pairResult';state.codeError=''}}else if(a==='codeBack'){state.mode='codeInput';state.unlocked=false;state.pass=''}else if(a==='unlock'){state.pass=document.getElementById('pass')?.value||state.pass;state.unlocked=state.pass.trim()===MONTHLY_PASSWORD}else if(a==='home'){state={...state,mode:'home'}}render()}
function answer(i){state.aAns.push(i);if(state.aAns.length<qs.length){state.step=state.aAns.length}else state.mode='soloResult';render()}
render();
