const MONTHLY_PASSWORD='午前2時';
const MBTI=['INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP'];
const qs=[
['🥂','初対面の飲み会であなたは？',[['自分から話しかける',{E:2},{party:2}],['話しかけられ待ち',{I:2},{distance:1}],['1人と深く話す',{I:1,N:1},{distance:2}],['様子を見る',{I:1,J:1},{care:2}]]],
['🍹','一杯目は？',[['とりあえずビール',{S:1,E:1},{party:2}],['ハイボール・サワー',{P:1,S:1},{party:1}],['カクテル・甘い系',{F:1,N:1},{music:1}],['ソフドリ・様子見',{J:2},{care:2}]]],
['💬','会話ではどっち？',[['自分の話をする',{E:2},{party:1}],['相手の話を聞く',{F:2},{distance:2}],['ツッコむ',{T:1,E:1},{party:1}],['深い話になる',{N:2},{distance:2}]]],
['🎤','二次会カラオケ、あなたは？',[['一番に歌う',{E:2,P:1},{karaoke:3}],['流れを見て入れる',{F:1,J:1},{care:1,karaoke:1}],['聴く専門',{I:2},{distance:1}],['気分で覚醒する',{P:2,N:1},{karaoke:2,midnight:1}]]],
['💗','気になる人が隣に来たら？',[['自分から話す',{E:1,F:1},{distance:2}],['相手待ち',{I:1,J:1},{care:1}],['ノリでいく',{E:1,P:1},{party:1,midnight:1}],['緊張して逆に静か',{I:2,F:1},{distance:1}]]],
['📱','LINEの返信は？',[['すぐ返す',{F:1,J:1},{care:1}],['気づいた時',{P:2},{midnight:1}],['相手次第',{F:1,N:1},{distance:1}],['わざと少し置く',{T:1,J:1},{care:1}]]],
['🎧','音楽の趣味が合わない相手は？',[['無理かも',{N:1,F:1},{music:3}],['少し大事',{F:1},{music:2}],['関係ない',{T:1,S:1},{care:1}],['むしろ新鮮',{N:1,P:1},{music:1,party:1}]]],
['🚃','終電が近い。あなたは？',[['帰る',{J:2},{care:2}],['少し迷う',{F:1,J:1},{distance:1}],['誰か残るなら残る',{E:1,F:1},{party:1}],['朝までコース',{P:2,E:1},{midnight:3,party:1}]]],
['🦙','酔ってくるとどうなる？',[['よく喋る',{E:2},{party:2}],['甘える',{F:2},{distance:2}],['静かになる',{I:2},{care:1}],['謎に元気',{P:2},{midnight:2,karaoke:1}]]],
['💘','好きになる人は？',[['面白い人',{E:1,P:1},{party:1}],['優しい人',{F:2},{distance:1}],['落ち着く人',{I:1,J:1},{care:1}],['刺激ある人',{N:1,P:1},{midnight:1}]]],
['🌙','二人きりで沈黙になったら？',[['気まずい',{E:1,F:1},{distance:1}],['自分から話す',{E:2},{party:1}],['平気',{I:1,T:1},{care:1}],['むしろ心地いい',{I:1,N:1},{distance:2}]]],
['✨','今このあと誘われたら？',[['もう一軒行く',{E:1,P:1},{party:2}],['ドライブ・散歩',{N:1,F:1},{distance:2}],['二人で話したい',{I:1,F:1},{distance:2}],['帰って寝る',{I:1,J:1},{care:2}]]]
];
const names={ENFP:['深夜エンターテイナー','距離感バグらせ小悪魔'],ENFJ:['飲み会プロデューサー','甘やかし沼メーカー'],ENTP:['ツッコミ無双の策士','口説き文句が冗談に聞こえる人'],ENTJ:['二次会支配人','主導権握りがちナイトリーダー'],ESFP:['朝までパーティー番長','その場の空気で恋が始まる人'],ESFJ:['みんなの世話焼き乾杯係','酔うと距離が近い世話焼き'],ESTP:['終電クラッシャー','終電後に強すぎる危険人物'],ESTJ:['幹事長タイプ','ちゃんとしてるのに夜だけ大胆'],INFP:['静かな沼タイプ','好きになると重めロマンチスト'],INFJ:['深夜の聞き上手','目が合うだけで沼らせる人'],INTP:['考えすぎ哲学酔い','理屈っぽいのに不意に甘い'],INTJ:['クールな観察者','落とす気ないのに刺さる人'],ISFP:['気分で覚醒アーティスト','雰囲気で全部持っていく人'],ISFJ:['安心感の毛布','安心させてから沼らせる人'],ISTP:['一匹狼カラオケ職人','無口なのに距離感がずるい'],ISTJ:['終電守護神','誠実そうで夜にギャップ出る人']};
const blurbs={ENFP:'その場を明るくする天才。好きな人には意外と考えすぎる朝3時タイプ。',ENFJ:'全員の空気を見て、気づけば場を支配しているやさしい司会者。',ENTP:'会話の瞬発力で距離を詰める。冗談の中に本音を混ぜがち。',ENTJ:'二次会の行き先も席順も決められる夜の司令塔。',ESFP:'楽しい空気の中心。勢いで一番ドラマを起こすタイプ。',ESFJ:'気配りでみんなを包む。酔うと少し距離が近くなる。',ESTP:'ノリと行動力の塊。終電後から本領発揮。',ESTJ:'ちゃんとしているから信頼される。だけど夜にギャップが出る。',INFP:'静かなのに記憶に残る。深い話で急に沼らせる。',INFJ:'聞き上手すぎて相手が勝手に心を開く。視線が強い。',INTP:'酔っても分析している。たまに出る甘さがずるい。',INTJ:'落ち着いた観察者。狙ってない一言が妙に刺さる。',ISFP:'気分が乗った瞬間だけ誰よりも魅力的。雰囲気で勝つ。',ISFJ:'安心感がすごい。気づいたら隣にいてほしい存在。',ISTP:'無口だけど行動で見せる。カラオケ選曲にセンスが出る。',ISTJ:'終電を守る理性派。誠実さとギャップでじわじわ強い。'};
let state={mode:'home',flow:'solo',step:0,person:'a',aType:'',bType:'',aAns:[],bAns:[],unlocked:false,pass:''};
const app=document.getElementById('app');
function typeFrom(ans,fb){if(fb)return fb;let s={E:0,I:0,S:0,N:0,T:0,F:0,J:0,P:0};ans.forEach((a,i)=>Object.entries(qs[i][2][a][1]).forEach(([k,v])=>s[k]+=v));return `${s.E>=s.I?'E':'I'}${s.S>=s.N?'S':'N'}${s.T>=s.F?'T':'F'}${s.J>=s.P?'J':'P'}`}
function night(ans){let n={party:0,karaoke:0,distance:0,midnight:0,music:0,care:0};ans.forEach((a,i)=>Object.entries(qs[i][2][a][2]||{}).forEach(([k,v])=>n[k]+=v));return n}
function comp(a,b,aa,ba){let sc=50;if(a[0]!=b[0])sc+=8;if(a[1]==b[1])sc+=8;if(a[2]!=b[2])sc+=6;if(a[3]!=b[3])sc+=8;[[6,10],[7,10],[10,10],[11,10]].forEach(([i,p])=>{if(aa[i]===ba[i])sc+=p;else if(Math.abs((aa[i]??0)-(ba[i]??0))===1)sc+=Math.floor(p/2)});if((aa[7]===0&&ba[7]===3)||(aa[7]===3&&ba[7]===0))sc-=12;if((aa[10]===0&&ba[10]===3)||(aa[10]===3&&ba[10]===0))sc-=8;return Math.max(32,Math.min(99,sc))}
function rank(sc){return sc>=90?'深夜まで一緒にいたくなる相性':sc>=80?'カラオケで距離が縮まる相性':sc>=70?'飲み会で自然に隣になる相性':sc>=60?'友達から始まる安定相性':'探り合いから始まる相性'}
function mbtiSelect(id,label,val){return `<label class="field"><span>${label}</span><select id="${id}"><option value="">未登録・わからない</option>${MBTI.map(t=>`<option ${val===t?'selected':''}>${t}</option>`).join('')}</select></label>`}
function render(){app.innerHTML=`<main class="wrap">${view()}</main>`;bind()}
function view(){if(state.mode==='home')return `<section class="card hero"><div><div class="badge">✨ 飲み会でバレる</div><h1>夜の16タイプ診断</h1><p>アルパカと一緒に見つける、あなたの裏人格。MBTI/16タイプ登録済みなら即診断。未登録でも12問で仮登録できます。</p><div class="actions"><button data-act="solo">💕 ひとりで診断する</button><button class="secondary" data-act="pair">👥 ふたりで相性診断する</button></div><p class="mini">※これはエンタメ用の16タイプ風診断です。</p></div><div><img src="alpaca-promo.png" alt="アルパカ夜診断"><div class="phone"><b>あなたのタイプは…</b><strong>ENFP</strong><span>小悪魔エンターテイナー</span></div></div></section>`;
if(state.mode==='gate')return `<section class="card center"><div class="alpaca">🦙💕</div><h2>まずMBTI/16タイプを登録してね</h2><p class="lead">登録済みなら選ぶだけ。わからない人は、このあと12問で夜タイプから仮判定します。</p><div class="grid2">${mbtiSelect('aType','あなたのMBTI',state.aType)}${state.flow==='pair'?mbtiSelect('bType','相手のMBTI',state.bType):''}</div><button data-act="gateNext">${canSkip()?'結果を見る':'12問で仮登録する'}</button><button class="ghost" data-act="home">戻る</button></section>`;
if(state.mode==='quiz'){let q=qs[state.step];return `<section class="card quiz"><div class="progress"><span>${state.person==='a'?'あなた':'相手'}の診断</span><b>${state.step+1}/12</b></div><div class="bar"><i style="width:${(state.step+1)/12*100}%"></i></div><div class="qIcon">${q[0]}</div><h2>${q[1]}</h2><div class="options">${q[2].map((o,i)=>`<button data-answer="${i}"><b>${String.fromCharCode(65+i)}</b>${o[0]}</button>`).join('')}</div></section>`}
let a=typeFrom(state.aAns,state.aType),b=typeFrom(state.bAns,state.bType),sc=state.flow==='pair'?comp(a,b,state.aAns,state.bAns):0,n=night(state.aAns);return `<section class="results"><div class="card result"><div class="alpaca">🦙✨</div><div class="badge">🍷 診断結果</div><h2>${a}</h2><h3>${names[a]?.[0]||'深夜エンターテイナー'}</h3><p class="lead">${blurbs[a]||blurbs.ENFP}</p>${stats(n)}<a class="btn share" target="_blank" href="https://twitter.com/intent/tweet?text=${encodeURIComponent(`飲み会でバレる夜人格診断をやったよ。私は${a}「${names[a]?.[0]}」だった 🦙💕`)}">結果をシェアする</a></div>${state.flow==='pair'?`<div class="card pair"><div class="badge">💕 ふたりの相性</div><h2>${sc}%</h2><h3>${rank(sc)}</h3><p>${a} × ${b}。音楽・終電・沈黙耐性から、今夜の距離感を判定しました。</p><ul><li>良いポイント：ノリか安心感のどちらかが噛み合いやすい</li><li>注意ポイント：深夜ノリの温度差は確認してから</li><li>おすすめ：カラオケか帰り道の散歩</li></ul></div>`:''}<div class="card secret"><h3>🔒 深夜モード</h3><p>合言葉を知っている人だけ、もう一段ドキッとする結果を見られます。</p>${state.unlocked?`<div class="unlocked"><h2>${names[a]?.[1]}</h2><p>急に攻めるより、帰り道の会話が一番刺さります。隣に座ると空気が変わるタイプ。</p>${state.flow==='pair'?`<b>深夜相性 ${Math.min(99,sc+7)}%</b>`:''}</div>`:`<input id="pass" placeholder="今月の合言葉" value="${state.pass}"><button data-act="unlock">深夜モードを解放する</button><small>ヒント：公式Xや画像のどこかに隠す想定</small>`}</div><button class="reset ghost" data-act="home">↻ もう一回やる</button></section>`}
function stats(n){return `<div class="stats">${[['飲み会ノリ',n.party],['カラオケ',n.karaoke],['距離感',n.distance],['深夜危険度',n.midnight],['音楽感性',n.music]].map(([k,v])=>`<div><span>${k}</span><i><b style="width:${Math.min(100,v*18)}%"></b></i></div>`).join('')}</div>`}
function canSkip(){return (state.flow==='solo'&&state.aType)||(state.flow==='pair'&&state.aType&&state.bType)}
function bind(){document.querySelectorAll('[data-act]').forEach(el=>el.onclick=()=>act(el.dataset.act));document.querySelectorAll('[data-answer]').forEach(el=>el.onclick=()=>answer(+el.dataset.answer));let at=document.getElementById('aType'),bt=document.getElementById('bType'),pass=document.getElementById('pass');if(at)at.onchange=e=>{state.aType=e.target.value;render()};if(bt)bt.onchange=e=>{state.bType=e.target.value;render()};if(pass)pass.oninput=e=>state.pass=e.target.value}
function act(a){if(a==='solo'||a==='pair'){state={mode:'gate',flow:a,step:0,person:'a',aType:'',bType:'',aAns:[],bAns:[],unlocked:false,pass:''}}else if(a==='home'){state={...state,mode:'home'}}else if(a==='gateNext'){if(canSkip())state.mode='result';else{state.person=!state.aType?'a':'b';state.step=0;state.mode='quiz'}}else if(a==='unlock'){state.unlocked=state.pass.trim()===MONTHLY_PASSWORD}render()}
function answer(i){let key=state.person==='a'?'aAns':'bAns';state[key].push(i);if(state[key].length<qs.length){state.step=state[key].length}else if(state.flow==='pair'&&state.person==='a'&&!state.bType){state.person='b';state.step=0}else state.mode='result';render()}
render();
